import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/nav";
import Footer from "@/components/ui/footer"
import AOSProvider from "@/components/ui/animation/AOS";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
      </head>
      <AOSProvider>
        <body className={`${inter.className} bg-[#fcfcf7]`}>
          <Navbar />
          {children}
          <Footer/>
        </body>
      </AOSProvider>

   
    </html>
  );
}
